@isTest  public class AsyncIEU_ERPMasterTest {

    @IsTest   public static void saveToken(){
        
      //     AddPagosGrupoInfoResponse_elementFuture.getValue();
        
     // new AsyncIEU_ERPMaster.AddPagosGrupoInfoResponse_elementFuture().getValue();
        
         new AsyncIEU_ERPMaster.AddPagosGrupoInfoResponse_elementFuture().getValue();
        
    //    AsyncIEU_ERPMaster obj =new AsyncIEU_ERPMaster();
     //   obj.AddPagosGrupoInfoResponse_elementFuture().getValue();
       //AsyncIEU_ERPMaster.AddPagosGrupoInfoResponse_elementFuture().getValue();
        
    }
}