@isTest public class GA_QueueableTest {
    @IsTest   public static void test(){
        
        Test.startTest();
//Queueable k = new MyQueueable();
       // GA_Queueable obj = new GA_Queueable();
    //    System.assertEquals( request.getMethod(), 'GET' ) ;
// Do any other initialization here
// This will perform the necessary deletes
//obj.execute();
// This will cause the recursive call from execute to fire
Test.stopTest();
    }
}